- src/PublicHoliday/BelgiumPublicHoliday.cs
- src/PublicHoliday/CanadaPublicHoliday.cs
- src/PublicHoliday/DutchPublicHoliday.cs
- src/PublicHoliday/FrancePublicHoliday.cs
- src/PublicHoliday/HolidayCalculator.cs
- src/PublicHoliday/IPublicHolidays.cs
- src/PublicHoliday/NorwayPublicHoliday.cs
- src/PublicHoliday/UKBankHoliday.cs
- src/PublicHoliday/USAPublicHoliday.cs
- tests/PublicHolidayTests/TestNorwayPublicHoliday.cs
@martinjw: Found out that we actually needed to calculate the previous working day before a holiday. So I added this method to the library. You can decide yourself if this is useful functionality. 
Two additional comments: when only looking a the name NextWorkingDay you expect that it does not return the same date if that day is a working day. So maybe there should be some kind of overload or two seperate methods?
The NextWorkingDay and PreviousWorkingDay methods needs to be copied over to each implementation. Maybe a PublicHoliday abstract base class can be useful to avoid these kind of code copies.
> Add previous working day method

- src/PublicHoliday/KazakhstanPublicHoliday.cs
- tests/PublicHolidayTests/TestKazakhstanPublicHoliday.cs
This does not reflect the fact that some holidays does not trigger moving to next working day, if happens on weekend. See the orthodox Christmas for that case. It is 7 Jan, but does not moved to 9 Jan in 2017 year in Kazakhstan
See http://egov.kz/cms/ru/articles/employment/holidays_calend
> Add Kazakhstan holidays

- src/PublicHoliday/PublicHoliday2015.csproj
- src/PublicHoliday/SwedenPublicHoliday.cs
- tests/PublicHolidayTests/PublicHolidayTests2015.csproj
- tests/PublicHolidayTests/TestSwedenPublicHoliday.cs
Added Swedish public holidays. Decided to include "de facto" holiday like Midsummer Eve. 
Depends on the intended audience what we want to include here...
http://www.officeholidays.com/countries/sweden/
https://www.timeanddate.com/holidays/sweden/
> Add Swedish public holidays (de facto holidays, 'eves off' are included)

- src/PublicHoliday/PublicHoliday2015.csproj
- Holiday.cs added to PublicHoliday2015.csproj
> Fixed build error in VS2015

- src/PublicHoliday/USAPublicHoliday.cs
- tests/PublicHolidayTests/TestUSPublicHoliday.cs
Making it not before 11/22.
Implementing in the same style as LaborDay and other holidays.
> Fix #25 - Thanksgiving is the 4th Thursday of November.

- src/PublicHoliday/UKBankHoliday.cs
- tests/PublicHolidayTests/TestUKBankHoliday.cs
This fixes the Early May Day Bank Holiday to be on the 8th May due to the 75th anniversary of VE day.
Note that as at this time this applies to England, Wales and NI but Scotland is yet to approve this (but is widely expected to, and I can't see where Scottish Bank Holidays are defined, as they are different)
> UK Early May Day 2020 moved

- src/PublicHoliday/NewZealandPublicHoliday.cs
- src/PublicHoliday/PublicHoliday.csproj
- tests/PublicHolidayTests/TestNewZealandPublicHoliday.cs
Dates for a new public holiday in New Zealand have been published by the New Zealand Government, adding this in as a holiday from 2022 onwards.
https://www.beehive.govt.nz/release/matariki-holiday-dates-next-thirty-years-announced
> Add dates for Matariki for the next 30 years

- src/PublicHoliday/NewZealandPublicHoliday.cs
- tests/PublicHolidayTests/TestNewZealandPublicHoliday.cs
Discovered while trying to fetch dates in the somewhat far future (2038) and was getting "System.ArgumentException: An item with the same key has already been added." whilst calling `PublicHolidayNames` for that year.
I also observed this happening for 2011 and confirmed that for this year that both holidays were observed on the same day (https://www.employment.govt.nz/leave-and-holidays/public-holidays/public-holidays-and-anniversary-dates/dates-for-previous-years/)
> ANZAC Day could share the same day as Easter Monday, so need to allow for this to happen

- src/PublicHoliday/AustraliaPublicHoliday.cs
- src/PublicHoliday/CanadaPublicHoliday.cs
- src/PublicHoliday/NewZealandPublicHoliday.cs
- tests/PublicHolidayTests/TestAustraliaPublicHoliday.cs
- tests/PublicHolidayTests/TestCanadaPublicHoliday.cs
- tests/PublicHolidayTests/TestNewZealandPublicHoliday.cs
#71 
Adding in one-off public holidays for Canada (State Funeral), Australia and New Zealand (National Day of Mourning) for recognising the death of Queen Elizabeth II
Refs:
https://www.smh.com.au/politics/federal/albanese-announces-public-holiday-to-mark-queen-s-death-20220911-p5bh4e.html
https://www.rnz.co.nz/news/national/474609/cabinet-announces-one-off-public-holiday-to-mark-death-of-queen-elizabeth-ii
> Add State Funeral for QEII for Canada, National Day of Mourning for Aus/NZ

- src/PublicHoliday/HolidayCalculator.cs
- src/PublicHoliday/SouthAfricaPublicHoliday.cs
- tests/PublicHolidayTests/TestSouthAfricaPublicHoliday.cs
For the SouthAfricaPublicHoliday implementation, the rules in South Africa are slightly different in that only public holidays that fall on a Sunday are carried over to the following Monday. Public holidays that fall on a Saturday do not get observed on another day. There are also some complexities around Christmas day and Boxing day.
I've added tests for all the scenarios and all tests are passing.
> South african public holidays fixes

- src/PublicHoliday/DutchPublicHoliday.cs
- tests/PublicHolidayTests/TestDutchPublicHoliday.cs
Fixes #95. 
Made it backwards compatible so it won’t break any installations but add the possibility to set the option if you need.
> Add option to specify Liberation Day is only at Lustrum years

- src/PublicHoliday/GermanPublicHoliday.cs
Added german holiday based on https://www.ndr.de/nachrichten/mecklenburg-vorpommern/Frauentag-in-MV-Landtag-beschliesst-neuen-Feiertag,frauentag370.html
> Added Womens Day for MV since 2023

- src/PublicHoliday/GermanPublicHoliday.cs
- tests/PublicHolidayTests/TestGermanyPublicHoliday.cs
Despite being sundays, Easter Sunday and Pentecost Sunday are formally declared as holidays in Brandenburg.
Source: [Public holidays in Germany](https://en.wikipedia.org/wiki/Public_holidays_in_Germany)
> Add missing holidays for Brandenburg

- src/PublicHoliday/GermanPublicHoliday.cs
- tests/PublicHolidayTests/TestGermanyPublicHoliday.cs
Assumption/Mariä Himmelfahrt is a public holiday in most parts of Bavaria (see https://www.statistik.bayern.de/mam/presse/2023/214_2023_44_a_mariae_himmelfahrt_2023.pdf)
so it should be included as public holiday.
> Germany: Assumption/Mariä Himmelfahrt is a public holiday in most parts of Bavaria

- src/PublicHoliday/SerbianPublicHoliday.cs
- tests/PublicHolidayTests/TestSerbianPublicHoliday.cs
Easter holidays and related tests were corrected for Serbia - Easter is Orthodox in Serbia.
> Fixed Easter related holidays for Serbia

- src/PublicHoliday/SouthAfricaPublicHoliday.cs
- tests/PublicHolidayTests/TestSouthAfricaPublicHoliday.cs
See presidential announcement for special holiday:
[President Ramaphosa declares 15 December a public holiday](https://www.sanews.gov.za/south-africa/president-ramaphosa-declares-15-december-public-holiday)
> South Africa - Special holiday - 2023 Rugby World Cup Win

- src/PublicHoliday/JapanPublicHoliday.cs
- tests/PublicHolidayTests/TestJapanPublicHoliday.cs
There was an algorithm to calculate Vernal and Autumnal Equinox Days for Japanese calendar. Although specific days for these holidays are announced every year by the government, it has never announced a different date.
> Fixed Japanese Equinox Day calculation

- src/PublicHoliday/JapanPublicHoliday.cs
- tests/PublicHolidayTests/TestJapanPublicHoliday.cs
Fixed case when Vernal or Autumnal Equinox day falls on Sunday. In this case the next Monday becomes a holiday.
> Fixed Japanese Vernal and Autumnal Equinox days 

- README.md
- src/PublicHoliday/BrazilPublicHoliday.cs
- src/PublicHoliday/HolidayCalculator.cs
- tests/PublicHolidayTests/TestBrazilPublicHoliday.cs
Added holidays for Brazil. 
The calendar holidays for Brazil 2024:
1/1/24 | segunda-feira | Confraternização Universal
-- | -- | --
12/2/24 | segunda-feira | Carnaval
13/2/24 | terça-feira | Carnaval
29/3/24 | sexta-feira | Paixão de Cristo
21/4/24 | domingo | Tiradentes
1/5/24 | quarta-feira | Dia do Trabalho
30/5/24 | quinta-feira | Corpus Christi
7/9/24 | sábado | Independência do Brasil
12/10/24 | sábado | Nossa Sr.a Aparecida - Padroeira do Brasil
2/11/24 | sábado | Finados
15/11/24 | sexta-feira | Proclamação da República
25/12/24 | quarta-feira | Natal
and 2025
1/1/25 | quarta-feira | Confraternização Universal
-- | -- | --
3/3/25 | segunda-feira | Carnaval
4/3/25 | terça-feira | Carnaval
18/4/25 | sexta-feira | Paixão de Cristo
21/4/25 | segunda-feira | Tiradentes
1/5/25 | …
> Added holidays for Brazil

- README.md
- src/PublicHoliday/CanadaPublicHoliday.cs
- src/PublicHoliday/PublicHoliday.csproj
- src/PublicHoliday/SwitzerlandPublicHoliday.cs
- tests/PublicHolidayTests/TestSwitzerlandPublicHoliday.cs
Update of the Switzerland section. In reality, Switzerland only has 4 official public holidays. Then it's up to each canton whether or not there are extra public holidays. 
I've been careful not to have a break-change, but now it's better to use a Canton enum as an argument.
> Update Switzerland Holiday with Cantons

- README.md
- src/PublicHoliday/USANewYorkStockExchangeHoliday.cs
- tests/PublicHolidayTests/TestUSNewYorkStockExchangeHoliday.cs
Copied holidays from US Public Holidays
Removed Veterans and Columbus days
Added Good Friday
Slight modification to Juneteenth since it was not observed by NYSE until 2022 instead of 2021.
Added similar unit tests
Update to README to reflect new holiday set
> NYSE holidays

- src/PublicHoliday/SouthAfricaPublicHoliday.cs
- tests/PublicHolidayTests/TestSouthAfricaPublicHoliday.cs
May 29th 2024 (South African election day), proclaimed a public holiday
[https://www.thepresidency.gov.za/president-proclaims-election-date-and-public-holiday](https://www.thepresidency.gov.za/president-proclaims-election-date-and-public-holiday)
> South Africa 2024 Election day

- src/PublicHoliday/PolandPublicHoliday.cs
- src/PublicHoliday/PublicHoliday.csproj
- tests/PublicHolidayTests/TestPolandPublicHoliday.cs
Added a method to calculate the date of Christmas Eve in response to the law signed by the President of Poland, Andrzej Duda, on Christmas Eve, December 24, 2024. The law, dated December 6, 2024, establishes Christmas Eve as a public holiday, effective February 1, 2025. 
Additionally, implemented dynamic calculations for Pentecost (49 days after Easter Sunday) and Corpus Christi (60 days after Easter Sunday), as these are moveable feasts dependent on the date of Easter. This update ensures compliance with Polish public holiday regulations and provides accurate holiday lists for any given year.
> Add method for calculating Christmas Eve date

- src/PublicHoliday/GermanPublicHoliday.cs
- tests/PublicHolidayTests/TestGermanyPublicHoliday.cs
Adds one-time public holidays for Berlin:
- 8 May 2025 (liberation day)
- 17 June 2028 (commemorating the 1953 East German uprising)
Fixes #146
> added Berlin state one-time holidays to GermanPublicHoliday

- src/PublicHoliday/AustraliaPublicHoliday.cs
- tests/PublicHolidayTests/TestAustraliaPublicHoliday.cs
NSW bank holidays are partial public holidays where banking and financial services businesses are closed.
An option to include NSW Bank Holidays as a public holiday when determining Australian public holidays is necessary for our use case and I believe it falls within the scope of this project.
Added a property to AustraliaPublicHoliday.cs
public bool IncludeNSWBankHoliday { get; set; } = false;
This bool defauilts to false so as to not affect existiing implementations of this package. 
When set to true, the output from a new public holiday definition:
public static DateTime BankHoliday(int year)
is added to the PublicHolidayNames andIsPublicHoliday methods
> option to add NSW bank holiday to Australian public holidays
