martinjw/Holiday

README.md, src/PublicHoliday/CanadaPublicHoliday.cs, src/PublicHoliday/HolidayCalculator.cs, tests/PublicHolidayTests/CanadaPublicHolidayTests.cs
I added support for Canadian provinces. It might not be perfect but it is a step in the right direction.
I also fixed a bug that was moving Canada day to the first Monday of July when it should be the 1st unless it is on a weekend.
I also added the civic holiday to the list of holiday's for Canada in general since it is recognized for federal employees.
=> Added Canadian provinces

src/PublicHoliday/Holiday.cs, src/PublicHoliday/IPublicHolidays.cs, src/PublicHoliday/PublicHolidayBase.cs, tests/PublicHolidayTests/TestPublicHolidayBase.cs
Added the ability to get holiday dates within a range. 
Holiday object was added for ease of use.
=> Added ability to get holidays in a date range

src/PublicHoliday/PublicHoliday2015.csproj, src/PublicHoliday/SlovakiaPublicHoliday.cs, tests/PublicHolidayTests/TestSlovakiaPublicHoliday.cs
Added public holidays in Slovakia, including historical holidays since 1952 (during the communism times).
Before that it might be inaccurate (used a guess or common sense and older time is not covered by unit tests). If anybody finds any sources about older holiday times let me know.
Unit tests are covered for many years where there was any change in a public holiday law.
=> Slovakia public holidays

README.md, src/PublicHoliday/AustriaPublicHoliday.cs, src/PublicHoliday/KazakhstanPublicHoliday.cs, src/PublicHoliday/PolandPublicHoliday.cs
- some fixes in comments (not modified languages in comments)
- updated README - added missing Austria and now the countries are ordered by alphabetical order
=> Cosmetic fixes and updated readme

README.md, src/PublicHoliday/CzechRepublicPublicHoliday.cs, src/PublicHoliday/EcbTargetClosingDay.cs, src/PublicHoliday/PublicHoliday2015.csproj, tests/PublicHolidayTests/TestCzechRepublicPublicHoliday.cs, tests/PublicHolidayTests/TestEcbTargetClosingDay.cs
- Added ECB SEPA TARGET closing days - useful if you are working with SEPA transactions or Euro currency exchange rates
- Added Czech Republic public holidays - all variations since 1925 (the oldest holiday law published and available on the Internet)
=> New holidays (CZ and ECB)

README.md, src/PublicHoliday/Holiday.cs, src/PublicHoliday/IPublicHolidays.cs, src/PublicHoliday/PublicHolidayBase.cs, src/PublicHoliday/USAPublicHoliday.cs
Added the ability to get observed and actual dates for US holidays, made the function virtual so it can be implemented for other countries as needed.
=> Added observed and holiday dates

src/PublicHoliday/PublicHolidayBase.cs
Since `NextWorkingDay(...)` is already virtual, I figured `PreviousWorkingDay(...)` should be also.
=> Change PreviousWorkingDay to virtual

src/PublicHoliday/NewZealandPublicHoliday.cs, tests/PublicHolidayTests/TestNewZealandPublicHoliday.cs
Fixed bug when both xmas and boxing day land on the weekend.
Added support to observe Anzac day.
=> Added support to observe Anzac day (NZ) and boxing day issue.

src/PublicHoliday/CanadaPublicHoliday.cs, src/PublicHoliday/DutchPublicHoliday.cs, src/PublicHoliday/PublicHoliday2015.csproj, src/PublicHoliday/SwitzerlandPublicHoliday.cs, tests/PublicHolidayTests/PublicHolidayTests2015.csproj, tests/PublicHolidayTests/TestSwitzerlandPublicHoliday.cs
Dear martinjw
I have added a calendar for Switzerland (with German holiday names). Feel free to take it up into your main branch! 
I have tried to be consistent with your coding style, tests have gone through without problems.
Sincerely, Oliver (olivsoft)
=> Added Switzerland Calendar

src/PublicHoliday/HolidayCalculator.cs, src/PublicHoliday/PublicHolidayBase.cs, tests/PublicHolidayTests/TestPublicHolidayBase.cs
Created an additional method to determine whether a given date is a working day. Achieved by refactoring logic into a separate method
=> Separate is working day

src/PublicHoliday/SouthAfricaPublicHoliday.cs, tests/PublicHolidayTests/TestSouthAfricaPublicHoliday.cs
New South Africa holidays and test functions
=> South Africa holidays

src/PublicHoliday/PolandPublicHoliday.cs
Added Polish diacritic characters.
=> Added polish diacritics

src/PublicHoliday/JapanPublicHoliday.cs
https://ja.wikipedia.org/wiki/%E5%A4%A9%E7%9A%87%E8%AA%95%E7%94%9F%E6%97%A5
>The date is February 23 (2020 or later), the birthday of the 126th Emperor Tokuhito.
=> modify EmperorsBirthday

src/PublicHoliday/ItalyPublicHoliday.cs
In Italy, Easter day is considered a holiday day. I retrieved it from HolidayCalculator.
=> Add Easter day holiday  for Italy

README.md, src/PublicHoliday/FinlandPublicHoliday.cs, tests/PublicHolidayTests/TestFinlandPublicHoliday.cs
Hi Martin! Great utility repo. Added Finland holidays, feel free to add them to marginjw/Holiday.
=> Add Finland holidays

src/PublicHoliday/DenmarkPublicHoliday.cs, tests/PublicHolidayTests/TestDenmarkPublicHoliday.cs
+small optimizations
Introduced as the smallest breaking change possible
https://www.ft.dk/samling/20222/lovforslag/L13/index.htm
=> Remove General Prayer Day as DK holiday from 2024

src/PublicHoliday/TurkeyPublicHoliday.cs, tests/PublicHolidayTests/TestTurkeyPublicHoliday.cs
I fixed the issue mentioned in case #87. This refactoring can also be applied to other countries if necessary.
=> Fix exception of public holidays that are on same day in Turkey

README.md, src/PublicHoliday/SerbianPublicHoliday.cs, tests/PublicHolidayTests/TestAllPublicHolidays.cs, tests/PublicHolidayTests/TestDenmarkPublicHoliday.cs, tests/PublicHolidayTests/TestSerbianPublicHoliday.cs
1. Added Serbian public holidays
2. Added tests for Serbian public holidays
3. Fixed test for Denmark holidays (There was a copy/paste error)
=> Added Serbian public holidays

src/PublicHoliday/UKBankHoliday.cs, tests/PublicHolidayTests/TestUKBankHoliday.cs
=> Fix UK Christmas when Boxing day on Monday

src/PublicHoliday/IrelandPublicHoliday.cs, tests/PublicHolidayTests/TestIrelandPublicHoliday.cs
=> Fixed StBrigid not being correct if 1st of February is a friday

src/PublicHoliday/IrelandPublicHoliday.cs, tests/PublicHolidayTests/TestIrelandPublicHoliday.cs
=> Fixed weekends adjusting when they shouldn't and May Day in IrelandPublicHoliday

src/PublicHoliday/PortugalPublicHoliday.cs, tests/PublicHolidayTests/TestPortugalPublicHoliday.cs
Hello,
Here is a proposal to include Portugal holidays into the library.
=> Add Portugal holidays

src/PublicHoliday/DenmarkPublicHoliday.cs, tests/PublicHolidayTests/TestDenmarkPublicHoliday.cs
There are additional Bank holidays in Denmark, so I've made an implementation.
Below is a link to "Danmarks Nationalbank" with a list of Bank holidays.
https://www.nationalbanken.dk/en/what-we-do/stable-prices-monetary-policy-and-the-danish-economy/bank-holidays
=> Add Denmark additional Bank holidays

src/PublicHoliday/JapanPublicHoliday.cs
https://github.com/martinjw/Holiday/issues/137
=> Fixes #137: Remove Japanese character from method name that causes compilation error on some system

README.md, src/PublicHoliday/HolidayCalculator.cs, src/PublicHoliday/PublicHolidayBase.cs, tests/PublicHolidayTests/PublicHolidayTests.csproj, tests/PublicHolidayTests/TestHolidayCalculator.cs
Add 2 methods for business days (Mon-Fri excluding holidays). Useful for SLAs/delivery times etc.
* BusinessDaysAdd(DateTime, int)
* BusinessDaysBetween(DateTime, DateTime)
=> Business days
